name=input("Your Name? ")
address=input("Your Address? ")
city=input("Name of your City? ")
state=input("State? ")
zipcode=input("zipcode? ")
telephone=input("What is your Telephone Number? ")
major=input("What is your College Major? ")
print('Name:'+ name)
print('Address: '+address)
print('         '+city +", "+zipcode)
print('Phone: '+telephone)